import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { WalletConnect } from '../components/WalletConnect'
import { motion, useScroll, useTransform, AnimatePresence } from 'framer-motion'
import { Send } from 'lucide-react'
import { HugeiconsIcon } from '@hugeicons/react'
import {
    ArrowUpRight01Icon,
    FlashIcon,
    Target02Icon,
    Shield02Icon,
    ArrowRight01Icon,
    Analytics01Icon,
    SecurityCheckIcon,
    Menu01Icon,
    Cancel01Icon
} from '@hugeicons/core-free-icons'

export default function Home() {
    const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
    // Static stats for Rogue
    const [activeFeature, setActiveFeature] = useState(0);
    const [stats] = useState([
        { label: 'ALPHA SIGNALS', value: '124', change: '+12' },
        { label: 'NARRATIVES TRACKED', value: '1.2K', change: '+50' },
        { label: 'SUCCESS RATE', value: '94%', change: '+2.1%' },
        { label: 'SOURCES SCANNED', value: '850+', change: '+45' },
    ])

    const features = [
        {
            id: '01',
            title: 'Ecosystem Scanning',
            description: '24/7 autonomous monitoring of X, Telegram, and on-chain flows. Our agents detect early movers before they trend on mainstream aggregators.',
            icon: ArrowUpRight01Icon,
            stats: [
                { label: 'SOURCES', value: '850+' },
                { label: 'LATENCY', value: '<50ms' }
            ]
        },
        {
            id: '02',
            title: 'High-Conviction Signals',
            description: 'Actionable trade setups with clear entry, target, and stop-loss levels generated by AI. We filter the noise to find the signal.',
            icon: FlashIcon,
            stats: [
                { label: 'ACCURACY', value: '94%' },
                { label: 'RR RATIO', value: '1:2' }
            ]
        },
        {
            id: '03',
            title: 'Token-Gated Speed',
            description: '$RGE holders receive 100% of signals via Telegram, up to 30 minutes before the curated public feed on X.',
            icon: Shield02Icon,
            stats: [
                { label: 'ADVANTAGE', value: '30m' },
                { label: 'ACCESS', value: 'TIER 1' }
            ]
        },
        {
            id: '04',
            title: 'Narrative Intelligence',
            description: 'Identify mindshare surges and sentiment shifts before the crowd. We track the "smart money" conversations so you don\'t have to.',
            icon: Analytics01Icon,
            stats: [
                { label: 'TOPICS', value: '1.2K' },
                { label: 'PREDICTION', value: 'AI-V2' }
            ]
        }
    ];

    useEffect(() => {
        console.log('Home mounted, checking for UnicornStudio...');
        // Script is already loaded in HTML, just initialize
        const initUnicorn = () => {
            console.log('Initializing UnicornStudio...');
            const UnicornStudio = (window as any).UnicornStudio;
            if (UnicornStudio) {
                try {
                    UnicornStudio.init();
                    console.log('UnicornStudio initialized successfully');
                } catch (error) {
                    console.error('Error initializing UnicornStudio:', error);
                }
            } else {
                console.error('UnicornStudio object not found on window during init');
            }
        };

        // Check if already loaded
        if ((window as any).UnicornStudio) {
            console.log('UnicornStudio found immediately');
            initUnicorn();
        } else {
            console.log('UnicornStudio not found immediately, starting interval check...');
            // Wait for script to load (it's in HTML head)
            const checkLoaded = setInterval(() => {
                if ((window as any).UnicornStudio) {
                    console.log('UnicornStudio found via interval');
                    clearInterval(checkLoaded);
                    initUnicorn();
                }
            }, 50);

            // Timeout after 5 seconds
            setTimeout(() => {
                clearInterval(checkLoaded);
                if (!(window as any).UnicornStudio) {
                    console.error('UnicornStudio load timed out after 5s');
                }
            }, 5000);

            return () => clearInterval(checkLoaded);
        }

    }, [])

    const { scrollY } = useScroll()
    const y1 = useTransform(scrollY, [0, 500], [0, 200])
    const y2 = useTransform(scrollY, [0, 500], [0, -150])

    return (
        <div className="min-h-screen bg-noir-black text-gray-100 font-sans selection:bg-teal-glow/30 selection:text-white overflow-x-hidden">

            {/* Header - Enhanced Glassmorphic */}
            <header className="fixed top-0 left-0 right-0 z-50 pt-6 px-6">
                <div className="max-w-7xl mx-auto rounded-full px-6 py-3 bg-noir-black/70 backdrop-blur-xl border border-white/10 shadow-2xl relative">
                    <div className="flex items-center justify-between">
                        <Link to="/" className="flex items-center gap-3 group">
                            <img src="/logo.webp" alt="Rogue Logo" className="w-8 h-8 rounded-full" />
                            <span className="text-white text-lg font-bold tracking-tight">ROGUE</span>
                        </Link>
                        <nav className="hidden md:flex items-center gap-1 text-sm font-medium text-white/60">
                            <a className="hover:text-white transition-colors duration-300 px-4 py-2 rounded-full hover:bg-white/5" href="#features">
                                Features
                            </a>
                            <a className="hover:text-white transition-colors duration-300 px-4 py-2 rounded-full hover:bg-white/5" href="#how-it-works">
                                How It Works
                            </a>
                            <Link className="hover:text-white transition-colors duration-300 px-4 py-2 rounded-full hover:bg-white/5" to="/app">
                                Terminal
                            </Link>
                            <Link className="hover:text-white transition-colors duration-300 px-4 py-2 rounded-full hover:bg-white/5" to="/docs">
                                Docs
                            </Link>
                        </nav>
                        <div className="hidden md:flex items-center gap-4">
                            <a 
                                href="https://t.me/rogueadkbot" 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-[#2AABEE]/10 border border-[#2AABEE]/20 text-[#2AABEE] hover:bg-[#2AABEE]/20 transition-colors group"
                            >
                                <Send className="w-4 h-4 group-hover:-translate-y-0.5 group-hover:translate-x-0.5 transition-transform" />
                                <span className="text-sm font-medium">Telegram Bot</span>
                            </a>
                            <WalletConnect />
                        </div>

                        {/* Mobile Menu Toggle */}
                        <button 
                            className="md:hidden text-white/80 hover:text-white p-1"
                            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
                        >
                            <HugeiconsIcon icon={isMobileMenuOpen ? Cancel01Icon : Menu01Icon} className="w-6 h-6" />
                        </button>
                    </div>
                </div>

                {/* Mobile Menu Overlay */}
                <AnimatePresence>
                    {isMobileMenuOpen && (
                        <motion.div
                            initial={{ opacity: 0, y: -10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -10 }}
                            className="absolute top-full left-6 right-6 mt-2 p-4 rounded-2xl bg-noir-black/95 backdrop-blur-xl border border-white/10 shadow-2xl md:hidden flex flex-col gap-2"
                        >
                            <a className="text-white/80 hover:text-white py-3 px-4 rounded-lg hover:bg-white/5 font-medium" href="#features" onClick={() => setIsMobileMenuOpen(false)}>Features</a>
                            <a className="text-white/80 hover:text-white py-3 px-4 rounded-lg hover:bg-white/5 font-medium" href="#how-it-works" onClick={() => setIsMobileMenuOpen(false)}>How It Works</a>
                            <Link className="text-white/80 hover:text-white py-3 px-4 rounded-lg hover:bg-white/5 font-medium" to="/app" onClick={() => setIsMobileMenuOpen(false)}>Terminal</Link>
                            <a className="text-white/80 hover:text-white py-3 px-4 rounded-lg hover:bg-white/5 font-medium" href="#">Docs</a>
                            <a 
                                href="https://t.me/rogueadkbot" 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="flex items-center gap-2 px-4 py-3 rounded-lg bg-[#2AABEE]/10 border border-[#2AABEE]/20 text-[#2AABEE] hover:bg-[#2AABEE]/20 transition-colors group font-medium"
                            >
                                <Send className="w-4 h-4 group-hover:-translate-y-0.5 group-hover:translate-x-0.5 transition-transform" />
                                <span>Telegram Bot</span>
                            </a>
                            <div className="pt-3 mt-1 border-t border-white/10 flex justify-center">
                                <WalletConnect />
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </header>

            {/* Hero Section with Animated Background */}
            <section className="relative pt-32 pb-20 md:pt-48 md:pb-32 overflow-hidden">
                {/* UnicornStudio Animated Background */}
                <div
                    data-us-project="4gq2Yrv2p0bIa0hdLPQx"
                    className="absolute inset-0 w-full h-full"
                    style={{
                        position: 'absolute',
                        top: 0,
                        left: 0,
                        width: '100%',
                        height: '100%',
                        zIndex: 0,
                        background: 'radial-gradient(circle at 50% 50%, rgba(0, 212, 255, 0.1) 0%, rgba(9, 10, 10, 0) 50%)',
                    }}
                />

                {/* Animated Background Elements - Fallback/Additional */}
                <div className="absolute inset-0 -z-20 overflow-hidden pointer-events-none">
                    <motion.div
                        style={{ y: y1, x: -100 }}
                        className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-teal-glow/10 rounded-full blur-[120px] opacity-30"
                    />
                    <motion.div
                        style={{ y: y2, x: 100 }}
                        className="absolute bottom-0 right-1/4 w-[600px] h-[600px] bg-teal-dark/10 rounded-full blur-[120px] opacity-30"
                    />
                    <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay"></div>
                </div>

                <div className="container mx-auto px-4 max-w-6xl relative z-10">
                    <div className="text-center">
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6 }}
                        >
                            <h1 className="text-5xl md:text-7xl lg:text-8xl font-bold mb-6 text-white tracking-tight leading-[0.95]">
                                ROGUE
                            </h1>
                        </motion.div>

                        <motion.p
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.2 }}
                            className="text-lg md:text-xl text-gray-400 mb-10 max-w-2xl mx-auto leading-relaxed"
                        >
                            The Real-Time Crypto Alpha Oracle. Relentlessly scanning the ecosystem to surface explosive low-cap opportunities and narrative shifts before they hit mainstream.
                        </motion.p>

                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.4 }}
                            className="flex flex-col sm:flex-row gap-4 justify-center mb-20"
                        >
                            <Link to="/app" className="inline-flex items-center justify-center gap-2 bg-teal-glow hover:bg-teal-dark text-noir-black px-8 py-4 rounded-lg text-base font-bold transition-all duration-300 shadow-[0_0_20px_rgba(0,212,255,0.3)] hover:shadow-[0_0_30px_rgba(0,212,255,0.5)]">
                                Open Terminal
                                <HugeiconsIcon icon={ArrowRight01Icon} size={20} />
                            </Link>
                            <Link to="/docs" className="inline-flex items-center justify-center gap-2 bg-white/5 hover:bg-white/10 text-white border border-white/10 px-8 py-4 rounded-lg text-base font-medium transition-all duration-300 backdrop-blur-sm">
                                Read Documentation
                            </Link>
                        </motion.div>

                        {/* Stats Bar */}
                        <motion.div
                            initial={{ opacity: 0, y: 40 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.8, delay: 0.6 }}
                            className="grid grid-cols-2 md:grid-cols-4 gap-4"
                        >
                            {stats.map((stat, i) => (
                                <div key={i} className="group rounded-xl bg-noir-dark/40 border border-white/5 p-6 backdrop-blur-sm hover:border-teal-glow/30 transition-all duration-300 hover:-translate-y-1">
                                    <div className="flex items-center justify-center gap-2 mb-2">
                                        {i === 0 && <HugeiconsIcon icon={Analytics01Icon} size={20} className="text-teal-glow" />}
                                        {i === 1 && <HugeiconsIcon icon={Target02Icon} size={20} className="text-teal-glow" />}
                                        {i === 2 && <HugeiconsIcon icon={ArrowUpRight01Icon} size={20} className="text-teal-glow" />}
                                        {i === 3 && <HugeiconsIcon icon={SecurityCheckIcon} size={20} className="text-teal-glow" />}
                                        <div className="text-3xl font-bold text-white">{stat.value}</div>
                                    </div>
                                    <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">{stat.label}</div>
                                    <div className="text-xs text-success font-mono font-medium bg-success/10 inline-block px-2 py-0.5 rounded">{stat.change}</div>
                                </div>
                            ))}
                        </motion.div>
                    </div>
                </div>
            </section>

            {/* Trusted By Section */}
            <section className="py-12 relative border-y border-white/5 bg-noir-black/50">
                <div className="max-w-7xl mx-auto px-4">
                    <div className="text-center mb-8">
                        <p className="uppercase text-xs font-medium text-gray-500 tracking-widest">
                            Analyzing signals from
                        </p>
                    </div>
                    <div className="overflow-hidden relative mask-linear-fade">
                        <div className="flex gap-16 py-2 items-center animate-marquee whitespace-nowrap">
                            {[...Array(2)].map((_, i) => (
                                <div key={i} className="flex gap-16 shrink-0 items-center min-w-full justify-around">
                                    <span className="text-xl font-bold text-gray-600 hover:text-white transition duration-300">FRAXTAL</span>
                                    <span className="text-xl font-bold text-gray-600 hover:text-white transition duration-300">SOLANA</span>
                                    <span className="text-xl font-bold text-gray-600 hover:text-white transition duration-300">BASE</span>
                                    <span className="text-xl font-bold text-gray-600 hover:text-white transition duration-300">ETHEREUM</span>
                                    <span className="text-xl font-bold text-gray-600 hover:text-white transition duration-300">ARBITRUM</span>
                                    <span className="text-xl font-bold text-gray-600 hover:text-white transition duration-300">COINGECKO</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </section>

            {/* Features Section - Interactive Terminal Tabs */}
            <section id="features" className="py-32 relative bg-noir-black overflow-hidden">
                {/* Background Grid */}
                <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px]"></div>
                <div className="absolute inset-0 bg-gradient-to-b from-noir-black via-transparent to-noir-black"></div>

                <div className="container mx-auto px-4 max-w-7xl relative z-10">
                    <div className="text-center mb-20">
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            className="inline-block mb-4 px-4 py-1.5 rounded-full border border-teal-glow/30 bg-teal-glow/5 text-teal-glow text-xs font-mono tracking-widest uppercase"
                        >
                            System Capabilities
                        </motion.div>
                        <motion.h2
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.1 }}
                            className="text-4xl md:text-6xl font-bold mb-6 text-white tracking-tight"
                        >
                            Why Choose <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-glow to-teal-500">Rogue</span>?
                        </motion.h2>
                        <motion.p
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.2 }}
                            className="text-xl text-gray-400 max-w-2xl mx-auto leading-relaxed"
                        >
                            The only oracle that combines social sentiment, on-chain data, and narrative analysis to find the next 100x.
                        </motion.p>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                        {/* Left Column: Navigation */}
                        <div className="lg:col-span-4 flex flex-col gap-4">
                            {features.map((feature, index) => (
                                <button
                                    key={index}
                                    onClick={() => setActiveFeature(index)}
                                    className={`group relative p-6 rounded-2xl border text-left transition-all duration-300 overflow-hidden ${
                                        activeFeature === index
                                            ? 'bg-teal-glow/5 border-teal-glow/50 shadow-[0_0_20px_rgba(0,212,255,0.1)]'
                                            : 'bg-noir-dark/30 border-white/5 hover:border-white/20 hover:bg-white/5'
                                    }`}
                                >
                                    <div className={`absolute left-0 top-0 bottom-0 w-1 transition-colors duration-300 ${
                                        activeFeature === index ? 'bg-teal-glow' : 'bg-transparent group-hover:bg-white/20'
                                    }`} />
                                    
                                    <div className="flex items-center gap-4">
                                        <span className={`font-mono text-sm ${
                                            activeFeature === index ? 'text-teal-glow' : 'text-gray-600'
                                        }`}>
                                            {feature.id}
                                        </span>
                                        <h3 className={`text-lg font-bold transition-colors ${
                                            activeFeature === index ? 'text-white' : 'text-gray-400 group-hover:text-white'
                                        }`}>
                                            {feature.title}
                                        </h3>
                                    </div>
                                </button>
                            ))}
                        </div>

                        {/* Right Column: Display Terminal */}
                        <div className="lg:col-span-8">
                            <div className="relative rounded-3xl bg-noir-dark/80 border border-white/10 overflow-hidden min-h-[500px] flex flex-col">
                                {/* Terminal Header */}
                                <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-black/20">
                                    <div className="flex items-center gap-2">
                                        <div className="flex gap-1.5">
                                            <div className="w-3 h-3 rounded-full bg-red-500/20 border border-red-500/50" />
                                            <div className="w-3 h-3 rounded-full bg-yellow-500/20 border border-yellow-500/50" />
                                            <div className="w-3 h-3 rounded-full bg-green-500/20 border border-green-500/50" />
                                        </div>
                                        <span className="ml-4 font-mono text-xs text-gray-500">TERMINAL_DISPLAY_V2.0</span>
                                    </div>
                                    <div className="flex items-center gap-2 font-mono text-xs text-teal-glow/70">
                                        <span className="w-2 h-2 rounded-full bg-teal-glow animate-pulse" />
                                        LIVE_FEED
                                    </div>
                                </div>

                                {/* Terminal Content */}
                                <div className="p-8 md:p-12 flex-1 flex flex-col relative">
                                    <AnimatePresence mode="wait">
                                        <motion.div
                                            key={activeFeature}
                                            initial={{ opacity: 0, x: 20 }}
                                            animate={{ opacity: 1, x: 0 }}
                                            exit={{ opacity: 0, x: -20 }}
                                            transition={{ duration: 0.3 }}
                                            className="h-full flex flex-col"
                                        >
                                            <div className="flex items-start justify-between mb-8">
                                                <div className="w-16 h-16 rounded-2xl bg-teal-glow/10 flex items-center justify-center border border-teal-glow/20">
                                                    <HugeiconsIcon 
                                                        icon={features[activeFeature].icon} 
                                                        size={32} 
                                                        className="text-teal-glow" 
                                                    />
                                                </div>
                                                <div className="font-mono text-4xl font-bold text-white/5">
                                                    {features[activeFeature].id}
                                                </div>
                                            </div>

                                            <h3 className="text-3xl md:text-4xl font-bold text-white mb-6">
                                                {features[activeFeature].title}
                                            </h3>
                                            
                                            <p className="text-xl text-gray-400 leading-relaxed mb-12 max-w-2xl">
                                                {features[activeFeature].description}
                                            </p>

                                            <div className="mt-auto grid grid-cols-2 gap-4">
                                                {features[activeFeature].stats.map((stat, i) => (
                                                    <div key={i} className="bg-white/5 rounded-xl p-4 border border-white/5">
                                                        <div className="text-xs text-gray-500 font-mono mb-1">{stat.label}</div>
                                                        <div className="text-2xl font-bold text-white">{stat.value}</div>
                                                    </div>
                                                ))}
                                            </div>
                                        </motion.div>
                                    </AnimatePresence>

                                    {/* Background Decoration */}
                                    <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay pointer-events-none" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Feature Showcase Section */}
            <section className="py-24 relative bg-noir-black">
                <div className="max-w-7xl mx-auto px-4 sm:px-8">
                    <div className="bg-noir-dark/40 border border-white/5 rounded-[2.5rem] p-8 md:p-12 backdrop-blur-sm overflow-hidden relative">
                        {/* Background Glow */}
                        <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-teal-glow/5 rounded-full blur-[100px] pointer-events-none" />

                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 items-center">
                            <div className="flex flex-col justify-between h-full">
                                <div>
                                    <span className="text-sm font-mono text-teal-glow tracking-wider uppercase">Platform</span>
                                    <h2 className="text-4xl md:text-6xl font-bold text-white tracking-tight mt-4 mb-8 leading-[1.1]">
                                        A platform for real-time Crypto Alpha.
                                    </h2>

                                    <div className="space-y-8 relative pl-6 border-l border-white/10">
                                        <div className="relative">
                                            <div className="absolute -left-[25px] top-1 w-3 h-3 rounded-full bg-teal-glow shadow-[0_0_10px_rgba(0,212,255,0.5)]" />
                                            <h3 className="text-xl font-bold text-white mb-2">Ecosystem Scanner</h3>
                                            <p className="text-gray-400">Relentlessly monitors X, Telegram, and on-chain data to surface opportunities before they trend.</p>
                                        </div>
                                        <div className="relative">
                                            <div className="absolute -left-[25px] top-1 w-3 h-3 rounded-full bg-teal-dark" />
                                            <h3 className="text-xl font-bold text-white mb-2">Signal Analyzer</h3>
                                            <p className="text-gray-400">Filters noise to identify high-conviction setups with clear entry, target, and stop-loss levels.</p>
                                        </div>
                                        <div className="relative">
                                            <div className="absolute -left-[25px] top-1 w-3 h-3 rounded-full bg-gray-600" />
                                            <h3 className="text-xl font-bold text-white mb-2">Alpha Publisher</h3>
                                            <p className="text-gray-400">Broadcasts all signals to $RGE holders instantly via Telegram. Curated highlights posted to X.</p>
                                        </div>
                                    </div>
                                </div>

                                <div className="mt-12">
                                    <Link to="/app" className="inline-flex items-center gap-2 text-teal-glow font-bold hover:text-white transition-colors group">
                                        Open Terminal
                                        <HugeiconsIcon icon={ArrowRight01Icon} size={20} className="group-hover:translate-x-1 transition-transform" />
                                    </Link>
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-4 relative">
                                <div className="space-y-4 mt-12">
                                    <div className="aspect-[4/5] rounded-2xl bg-noir-black border border-white/10 p-4 relative overflow-hidden group hover:border-teal-glow/30 transition-colors">
                                        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-noir-black/90 z-10" />
                                        <div className="absolute bottom-4 left-4 z-20">
                                            <div className="text-xs text-teal-glow font-mono mb-1">MONITORING</div>
                                            <div className="text-lg font-bold text-white">Live Tracking</div>
                                        </div>
                                        {/* Abstract UI representation */}
                                        <img src="/live-tracking.webp" alt="Live Tracking" className="w-full h-full object-cover rounded-lg" />
                                    </div>
                                    <div className="aspect-[4/3] rounded-2xl bg-noir-black border border-white/10 p-4 relative overflow-hidden group hover:border-teal-glow/30 transition-colors">
                                        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-noir-black/90 z-10" />
                                        <div className="absolute bottom-4 left-4 z-20">
                                            <div className="text-xs text-teal-glow font-mono mb-1">SECURITY</div>
                                            <div className="text-lg font-bold text-white">Risk Analysis</div>
                                        </div>
                                        <img src="/risk-analysis.webp" alt="Risk Analysis" className="w-full h-full object-cover rounded-lg" />
                                    </div>
                                </div>
                                <div className="space-y-4">
                                    <div className="aspect-[4/3] rounded-2xl bg-noir-black border border-white/10 p-4 relative overflow-hidden group hover:border-teal-glow/30 transition-colors">
                                        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-noir-black/90 z-10" />
                                        <div className="absolute bottom-4 left-4 z-20">
                                            <div className="text-xs text-teal-glow font-mono mb-1">STRATEGY</div>
                                            <div className="text-lg font-bold text-white">Multi-Chain</div>
                                        </div>
                                        <img src="/multi-chain.webp" alt="Multi-Chain" className="w-full h-full object-cover rounded-lg" />
                                    </div>
                                    <div className="aspect-[4/5] rounded-2xl bg-noir-black border border-white/10 p-4 relative overflow-hidden group hover:border-teal-glow/30 transition-colors">
                                        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-noir-black/90 z-10" />
                                        <div className="absolute bottom-4 left-4 z-20">
                                            <div className="text-xs text-teal-glow font-mono mb-1">AI</div>
                                            <div className="text-lg font-bold text-white">Smart Optimization</div>
                                        </div>
                                        <img src="/smart-optimization.webp" alt="Smart Optimization" className="w-full h-full object-cover rounded-lg" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* How It Works Section - Cyberpunk Pipeline */}
            <section id="how-it-works" className="py-32 relative bg-noir-black overflow-hidden">
                <div className="container mx-auto px-4 max-w-7xl relative z-10">
                    <div className="text-center mb-24">
                        <motion.h2
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            className="text-4xl md:text-6xl font-bold mb-6 text-white tracking-tight"
                        >
                            Initialization <span className="text-teal-glow">Sequence</span>
                        </motion.h2>
                        <motion.p
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.1 }}
                            className="text-xl text-gray-400"
                        >
                            Establish uplink to the Rogue network in three stages.
                        </motion.p>
                    </div>

                    <div className="relative">
                        {/* Connecting Line */}
                        <div className="hidden md:block absolute top-1/2 left-0 w-full h-0.5 bg-white/10 -translate-y-1/2 z-0"></div>
                        <div className="hidden md:block absolute top-1/2 left-0 w-full h-0.5 bg-teal-glow/50 -translate-y-1/2 z-0 scale-x-0 origin-left animate-[grow_3s_ease-in-out_infinite]"></div>

                        <div className="grid grid-cols-1 md:grid-cols-3 gap-12 relative z-10">
                            {[
                                { step: '01', title: 'Connect Wallet', desc: 'Authenticate your identity via Web3 wallet connection.', icon: FlashIcon },
                                { step: '02', title: 'Verify Clearance', desc: 'System checks $RGE holdings to determine your access tier.', icon: Shield02Icon },
                                { step: '03', title: 'Receive Intel', desc: 'Uplink established. Real-time alpha streams directly to your terminal.', icon: Analytics01Icon },
                            ].map((item, i) => (
                                <motion.div
                                    key={i}
                                    initial={{ opacity: 0, y: 30 }}
                                    whileInView={{ opacity: 1, y: 0 }}
                                    viewport={{ once: true }}
                                    transition={{ delay: i * 0.2 }}
                                    className="group relative"
                                >
                                    <div className="bg-noir-dark border border-white/10 rounded-2xl p-8 relative overflow-hidden hover:border-teal-glow/50 transition-all duration-500 hover:-translate-y-2">
                                        <div className="absolute top-0 right-0 p-4 opacity-10 text-6xl font-bold font-mono group-hover:opacity-20 transition-opacity">
                                            {item.step}
                                        </div>
                                        <div className="w-16 h-16 rounded-full bg-noir-black border border-teal-glow/30 flex items-center justify-center text-3xl mb-6 shadow-[0_0_15px_rgba(0,212,255,0.2)] group-hover:shadow-[0_0_25px_rgba(0,212,255,0.4)] transition-shadow mx-auto md:mx-0">
                                            <HugeiconsIcon icon={item.icon} size={32} className="text-teal-glow" />
                                        </div>
                                        <h3 className="text-2xl font-bold text-white mb-3 text-center md:text-left">{item.title}</h3>
                                        <p className="text-gray-400 leading-relaxed text-center md:text-left">{item.desc}</p>
                                        
                                        {/* Progress Bar */}
                                        <div className="mt-6 w-full bg-white/5 h-1 rounded-full overflow-hidden">
                                            <div className={`h-full bg-teal-glow transition-all duration-1000 ease-out ${i === 0 ? 'w-1/3' : i === 1 ? 'w-2/3' : 'w-full'} group-hover:w-full`}></div>
                                        </div>
                                    </div>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.6 }}
                        className="text-center mt-20"
                    >
                        <Link to="/app" className="inline-flex items-center justify-center gap-3 bg-teal-glow hover:bg-teal-dark text-noir-black px-10 py-5 rounded-lg text-lg font-bold transition-all duration-300 shadow-[0_0_20px_rgba(0,212,255,0.3)] hover:shadow-[0_0_40px_rgba(0,212,255,0.5)] hover:scale-105">
                            <span className="relative flex h-3 w-3">
                              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-noir-black opacity-75"></span>
                              <span className="relative inline-flex rounded-full h-3 w-3 bg-noir-black"></span>
                            </span>
                            INITIATE SEQUENCE
                            <HugeiconsIcon icon={ArrowRight01Icon} size={24} />
                        </Link>
                    </motion.div>
                </div>
            </section>

            {/* CTA Section - Terminal Portal */}
            <section className="py-32 relative overflow-hidden">
                <div className="absolute inset-0 bg-noir-black">
                    <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay"></div>
                    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-teal-glow/10 rounded-full blur-[120px] animate-pulse"></div>
                </div>

                <div className="container mx-auto px-4 max-w-5xl relative z-10">
                    <motion.div
                        initial={{ scale: 0.9, opacity: 0 }}
                        whileInView={{ scale: 1, opacity: 1 }}
                        viewport={{ once: true }}
                        className="rounded-[3rem] bg-noir-dark/80 backdrop-blur-xl border border-teal-glow/30 p-12 md:p-24 text-center relative overflow-hidden group"
                    >
                        {/* Animated Border Gradient */}
                        <div className="absolute inset-0 bg-gradient-to-r from-transparent via-teal-glow/20 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-1000 ease-in-out"></div>
                        
                        <div className="relative z-10">
                            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-teal-glow/10 border border-teal-glow/20 text-teal-glow font-mono text-sm mb-8">
                                <span className="w-2 h-2 rounded-full bg-teal-glow animate-pulse"></span>
                                SYSTEM STATUS: ONLINE
                            </div>
                            
                            <h2 className="text-5xl md:text-7xl font-bold mb-8 text-white tracking-tight leading-tight">
                                Ready to <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-glow to-white">Go Rogue</span>?
                            </h2>
                            
                            <p className="text-xl md:text-2xl text-gray-400 mb-12 max-w-3xl mx-auto leading-relaxed">
                                The terminal is open. The signals are live. Join the elite network of alpha hunters today.
                            </p>
                            
                            <div className="flex flex-col sm:flex-row gap-6 justify-center items-center">
                                <Link to="/app" className="w-full sm:w-auto inline-flex items-center justify-center gap-3 bg-teal-glow hover:bg-teal-dark text-noir-black px-12 py-6 rounded-xl text-xl font-bold transition-all duration-300 shadow-[0_0_30px_rgba(0,212,255,0.4)] hover:shadow-[0_0_50px_rgba(0,212,255,0.6)] hover:-translate-y-1">
                                    ENTER TERMINAL
                                    <HugeiconsIcon icon={ArrowRight01Icon} size={24} />
                                </Link>
                                <a href="https://t.me/rogueadkbot" target="_blank" rel="noopener noreferrer" className="w-full sm:w-auto inline-flex items-center justify-center gap-3 bg-white/5 hover:bg-white/10 text-white border border-white/10 px-12 py-6 rounded-xl text-xl font-bold transition-all duration-300 backdrop-blur-sm hover:border-teal-glow/30">
                                    <Send className="w-5 h-5" />
                                    JOIN TELEGRAM
                                </a>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </section>

            {/* Footer */}
            <footer className="border-t border-white/5 bg-noir-black py-16">
                <div className="container mx-auto px-4 max-w-6xl">
                    <div className="grid md:grid-cols-4 gap-12 mb-12">
                        <div className="col-span-1 md:col-span-1">
                            <div className="flex items-center gap-2 mb-6">
                                <img src="/logo.webp" alt="Rogue Logo" className="w-8 h-8 rounded-full" />
                                <span className="text-white text-xl font-bold">ROGUE</span>
                            </div>
                            <p className="text-sm text-gray-500 leading-relaxed">
                                The Real-Time Crypto Alpha Oracle.
                            </p>
                        </div>
                        <div>
                            <h4 className="text-white font-bold mb-6">Product</h4>
                            <ul className="space-y-4 text-sm text-gray-500">
                                <li><a href="#features" className="hover:text-teal-glow transition-colors">Features</a></li>
                                <li><a href="#how-it-works" className="hover:text-teal-glow transition-colors">How It Works</a></li>
                                <li><Link to="/app" className="hover:text-teal-glow transition-colors">Terminal</Link></li>
                            </ul>
                        </div>
                        <div>
                            <h4 className="text-white font-bold mb-6">Resources</h4>
                            <ul className="space-y-4 text-sm text-gray-500">
                                <li><Link to="/docs" className="hover:text-teal-glow transition-colors">Documentation</Link></li>
                            </ul>
                        </div>
                        <div>
                            <h4 className="text-white font-bold mb-6">Community</h4>
                            <ul className="space-y-4 text-sm text-gray-500">
                                <li><a href="https://x.com/Rogue_IQAI" target="_blank" rel="noopener noreferrer" className="hover:text-teal-glow transition-colors">X (Twitter)</a></li>
                                <li><a href="https://t.me/rogueadkbot" target="_blank" rel="noopener noreferrer" className="hover:text-teal-glow transition-colors">Telegram</a></li>
                                <li><a href="https://github.com/zaikaman/RogueAgent" target="_blank" rel="noopener noreferrer" className="hover:text-teal-glow transition-colors">GitHub</a></li>
                            </ul>
                        </div>
                    </div>
                    <div className="pt-8 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-4">
                        <p className="text-xs text-gray-600">
                            © 2025 Rogue. All rights reserved.
                        </p>
                    </div>
                </div>
            </footer>
        </div>
    )
}

// Add type declaration for UnicornStudio
declare global {
    interface Window {
        UnicornStudio?: {
            init: () => void;
            isInitialized?: boolean;
        };
    }
}