import { useRunStatus } from '../hooks/useRunStatus';
import { useSignalsHistory } from '../hooks/useSignals';
import { SignalCard } from '../components/SignalCard';
import { HugeiconsIcon } from '@hugeicons/react';
import { GpsSignal01Icon, Loading03Icon } from '@hugeicons/core-free-icons';

export function SignalsPage() {
  const { data: runStatus, isLoading: isStatusLoading } = useRunStatus();
  const { data: historyData, isLoading: isHistoryLoading } = useSignalsHistory();
  
  const latestSignal = runStatus?.latest_signal;
  const historySignals = historyData?.data || [];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <HugeiconsIcon icon={GpsSignal01Icon} className="w-6 h-6 text-cyan-500" />
            Signals
          </h2>
          <p className="text-gray-400 mt-1">Real-time alpha signals generated by the swarm.</p>
        </div>
      </div>

      {/* Latest Signal */}
      <div className="space-y-4">
        <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider">Latest Signal</h3>
        <SignalCard signal={latestSignal} isLoading={isStatusLoading} />
      </div>

      {/* History */}
      <div className="space-y-4 pt-8 border-t border-gray-800">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider">Signal History</h3>
          {isHistoryLoading && (
            <HugeiconsIcon icon={Loading03Icon} className="w-4 h-4 text-cyan-500 animate-spin" />
          )}
        </div>
        
        {historySignals.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {historySignals.map((signal: any) => (
              <SignalCard key={signal.id} signal={signal} />
            ))}
          </div>
        ) : (
          !isHistoryLoading && (
            <div className="bg-gray-900/30 border border-gray-800 rounded-xl p-8 text-center">
              <p className="text-gray-500">No signal history available.</p>
            </div>
          )
        )}
      </div>
    </div>
  );
}
