/**
 * Mapping of token symbols to their CoinGecko IDs
 * Used to normalize coingecko_id for price tracking in signal monitoring
 * 
 * This mapping covers all tokens tradeable on Hyperliquid perpetuals
 * Last updated: November 2025
 */

export const SYMBOL_TO_COINGECKO_ID: Record<string, string> = {
  // Major coins
  'BTC': 'bitcoin',
  'ETH': 'ethereum',
  'SOL': 'solana',
  'BNB': 'binancecoin',
  'XRP': 'ripple',
  'ADA': 'cardano',
  'AVAX': 'avalanche-2',
  'DOGE': 'dogecoin',
  'DOT': 'polkadot',
  'LINK': 'chainlink',
  'LTC': 'litecoin',
  'BCH': 'bitcoin-cash',
  'ETC': 'ethereum-classic',
  'ATOM': 'cosmos',
  'UNI': 'uniswap',
  'AAVE': 'aave',
  'MKR': 'maker',
  'SNX': 'havven',
  'COMP': 'compound-governance-token',
  'CRV': 'curve-dao-token',

  // Layer 2 & Infrastructure
  'ARB': 'arbitrum',
  'OP': 'optimism',
  'MATIC': 'matic-network',
  'POL': 'matic-network', // POL is the new ticker for MATIC
  'STRK': 'starknet',
  'MANTA': 'manta-network',
  'BLAST': 'blast',
  'ZK': 'zksync',
  'SCROLL': 'scroll',
  'ZETA': 'zetachain',
  'METIS': 'metis-token',
  'CELO': 'celo',
  'NEAR': 'near',
  'ICP': 'internet-computer',
  'FIL': 'filecoin',
  'AR': 'arweave',
  'RENDER': 'render-token',
  'RNDR': 'render-token',

  // DeFi
  'DYDX': 'dydx-chain',
  'GMX': 'gmx',
  'LDO': 'lido-dao',
  'FXS': 'frax-share',
  'PENDLE': 'pendle',
  'EIGEN': 'eigenlayer',
  'ETHFI': 'ether-fi',
  'ENA': 'ethena',
  'ONDO': 'ondo-finance',
  'MORPHO': 'morpho',
  'USUAL': 'usual',
  'LISTA': 'lista-dao',
  'AERO': 'aerodrome-finance',
  'CAKE': 'pancakeswap-token',
  'SUSHI': 'sushi',
  'BADGER': 'badger-dao',
  'RSR': 'reserve-rights-token',
  'RDNT': 'radiant-capital',

  // Gaming & Metaverse
  'IMX': 'immutable-x',
  'GALA': 'gala',
  'SAND': 'the-sandbox',
  'APE': 'apecoin',
  'ILV': 'illuvium',
  'YGG': 'yield-guild-games',
  'BIGTIME': 'bigtime',
  'PIXEL': 'pixels',
  'SUPER': 'superfarm',
  'MAVIA': 'heroes-of-mavia',
  'PRIME': 'echelon-prime',
  'XAI': 'xai-games',
  'BEAM': 'beam-2',
  'PORTAL': 'portal-2',
  'ACE': 'fusionist',
  'RON': 'ronin',

  // AI & Data
  'FET': 'fetch-ai',
  'TAO': 'bittensor',
  'IO': 'io-net',
  'GRASS': 'grass',
  'AI16Z': 'ai16z',
  'AIXBT': 'aixbt',
  'VIRTUAL': 'virtual-protocol',
  'GRIFFAIN': 'griffain',
  'AI': 'sleepless-ai',
  'PROMPT': 'wayfinder',
  'KAITO': 'kaito',

  // Meme coins
  'SHIB': 'shiba-inu',
  'PEPE': 'pepe',
  'BONK': 'bonk',
  'FLOKI': 'floki',
  'WIF': 'dogwifcoin',
  'POPCAT': 'popcat',
  'BRETT': 'brett',
  'NEIRO': 'neiro-3',
  'GOAT': 'goatseus-maximus',
  'PNUT': 'peanut-the-squirrel',
  'MOODENG': 'moo-deng',
  'FARTCOIN': 'fartcoin',
  'ZEREBRO': 'zerebro',
  'TURBO': 'turbo',
  'MEME': 'memecoin-2',
  'MYRO': 'myro',
  'MEW': 'cat-in-a-dogs-world',
  'BOME': 'book-of-meme',
  'CHILLGUY': 'chill-guy',
  'DOOD': 'doodles',
  'SPX': 'spx6900',
  'HPOS': 'ethereum-is-good',
  'PURR': 'purr-2',
  'NEIROETH': 'neiro-2',
  // k-prefixed tokens (usually smaller denomination versions)
  'kBONK': 'bonk',
  'kDOGS': 'dogs-2',
  'kFLOKI': 'floki',
  'kLUNC': 'terra-luna',
  'kNEIRO': 'neiro-3',
  'kPEPE': 'pepe',
  'kSHIB': 'shiba-inu',

  // Political & Social
  'TRUMP': 'official-trump',
  'MELANIA': 'melania-meme',
  'PEOPLE': 'constitutiondao',
  'FRIEND': 'friend-tech',
  'VINE': 'vine-coin',
  'WLFI': 'world-liberty-financial',

  // New ecosystems
  'SUI': 'sui',
  'SEI': 'sei-network',
  'TIA': 'celestia',
  'APT': 'aptos',
  'INJ': 'injective-protocol',
  'PYTH': 'pyth-network',
  'JTO': 'jito-governance-token',
  'JUP': 'jupiter-exchange-solana',  // <-- This is the key fix for your JUP issue!
  'W': 'wormhole',
  'DYM': 'dymension',
  'ALT': 'altlayer',
  'BERA': 'berachain-bera',
  'INIT': 'initia',
  'HYPE': 'hyperliquid',
  'HYPER': 'hyperliquid',
  'IP': 'story-2',
  'MOVE': 'movement',
  'LAYER': 'layer-ai',
  'S': 'sonic-3',
  'ANIME': 'animecoin',
  'MON': 'monad', // Note: May need update when Monad launches
  'BABY': 'baby',
  'LAUNCHCOIN': 'believe-in-something',
  'PUMP': 'pump',

  // Infrastructure & Utilities
  'STX': 'blockstack',
  'KAS': 'kaspa',
  'TON': 'the-open-network',
  'TRX': 'tron',
  'XLM': 'stellar',
  'ALGO': 'algorand',
  'HBAR': 'hedera-hashgraph',
  'NEO': 'neo',
  'ZEC': 'zcash',
  'BSV': 'bitcoin-cash-sv',
  'ORDI': 'ordinals',
  'WLD': 'worldcoin-wld',
  'BLUR': 'blur',
  'ENS': 'ethereum-name-service',
  'GAS': 'gas',
  'BLZ': 'bluzelle',
  'OGN': 'origin-protocol',
  'APEX': 'apex-token-2',
  'CYBER': 'cyberconnect',

  // Others
  'FTM': 'fantom',
  'RUNE': 'thorchain',
  'NOT': 'notcoin',
  'HMSTR': 'hamster-kombat',
  'CATI': 'catizen',
  'DOGS': 'dogs-2',
  'OM': 'mantra-dao',
  'OMNI': 'omni-network',
  'SAGA': 'saga-2',
  'TNSR': 'tensor',
  'REZ': 'renzo',
  'MERL': 'merlin-chain',
  'BIO': 'bio-protocol',
  'PENGU': 'pudgy-penguins',
  'ME': 'magic-eden',
  'PAXG': 'pax-gold',
  'RLB': 'rollbit-coin',
  'UNIBOT': 'unibot',
  'GMT': 'stepn',
  'BANANA': 'apeswap-finance',
  'MAV': 'maverick-protocol',
  'TRB': 'tellor',
  'STG': 'stargate-finance',
  'UMA': 'uma',
  'BNT': 'bancor',
  'ARK': 'ark',
  'NTRN': 'neutron-3',
  'IOTA': 'iota',
  'MINA': 'mina-protocol',
  'CFX': 'conflux-token',
  'CANTO': 'canto',
  'MNT': 'mantle',
  'LOOM': 'loom-network-new',
  'REQ': 'request-network',
  'USTC': 'terrausd',
  'FTT': 'ftx-token',
  'ZEN': 'horizen',
  'ORBS': 'orbs',
  'POLYX': 'polymesh',
  'STRAX': 'stratis',
  'PANDORA': 'pandora',
  'OX': 'ox-coin',
  'CC': 'canton-network', // Canton Network

  // Newer additions (Nov 2025)
  'MEGA': 'mega-dice',
  '0G': 'og',
  '2Z': 'toadzcoins',
  'ASTER': 'aster-protocol',
  'AVNT': 'avant-network',
  'HEMI': 'hemi',
  'JELLY': 'jelly-meme',
  'MET': 'metars-genesis',
  'NIL': 'nil',
  'NXPC': 'nxpc',
  'PROVE': 'provenance-blockchain',
  'SCR': 'scroll',
  'SKY': 'sky',
  'SOPH': 'sophiaverse',
  'STBL': 'hyperstable',
  'SYRUP': 'maple',
  'TST': 'tst',
  'VVV': 'venice-token',
  'WCT': 'walletconnect',
  'XPL': 'pulse',
  'YZY': 'yeay',
  'ZORA': 'zora',
  'ZRO': 'layerzero',
};

/**
 * Get the CoinGecko ID for a given symbol
 * Falls back to lowercase symbol if no mapping exists
 */
export function getCoingeckoId(symbol: string): string {
  const upperSymbol = symbol.toUpperCase().replace(/USDT$/, '').replace(/-PERP$/, '');
  return SYMBOL_TO_COINGECKO_ID[upperSymbol] || symbol.toLowerCase();
}

/**
 * Check if we have a known CoinGecko mapping for a symbol
 */
export function hasCoingeckoMapping(symbol: string): boolean {
  const upperSymbol = symbol.toUpperCase().replace(/USDT$/, '').replace(/-PERP$/, '');
  return upperSymbol in SYMBOL_TO_COINGECKO_ID;
}
